### ISSUE TITLE
Map Showing deployables (tents, hedgehogs,..) from all instances.

### ISSUE THREAD

**Issue by Cookiezzz** [zamp/DayZMapper#22]
If you are running multiple instances, the map will show all deployables from every instance.

Easy fix:

data.php
below line 101 (    deployable d on d.id = id.deployable_id)
add this: 

WHERE
    id.instance_id = " . $db->quote($config['instance']) . "

**Comment by Skaronator** [comment]
Do you think so?

**Comment by Cookiezzz** [comment]
You forgot the 'WHERE' (without quotes ofcourse)

it's part of the code you have to add.
without 'WHERE' it will crash

**Comment by Skaronator** [comment]
Okay, Right?

**Comment by Cookiezzz** [comment]
Looks oke to me this time
