### ISSUE TITLE
Not showing map

### ISSUE THREAD

**Issue by 123coolguy77** [zamp/DayZMapper#28]
This is all that it shows http://i.imgur.com/0vy4f.jpg

**Comment by zamp** [comment]
Update to the latest version and check the error. It should include a more elaborate error message now.

**Comment by 123coolguy77** [comment]
Now it says Refresh failed: [0ErrorEvent type="ioError" bubbles=false cancelable-false evenPhase=2 text="error #2023"]

**Comment by Skaronator** [comment]
Same Error.

**Comment by zamp** [comment]
You sure it's 2023 and not 2032? If it's 2032 then it means the mapper can't find data.php
Try accessing the data.php directly. Enter http://yourmapper_url/data.php it should print out xml formatted plain text.

**Comment by zamp** [comment]
Just noticed the install guide tells you to copy one map file but doesn't specify where. The map.txt file has to be where the dayzmapper.swf file is.

**Comment by Skaronator** [comment]
Okay working now!
When I have time I make a better mapfile of Lingor

**Comment by 123coolguy77** [comment]
data.php gives a xml formatted plain text page and map.txt is in the correct spot
