### ISSUE TITLE
Oring Map

### ISSUE THREAD

**Issue by khamseen** [zamp/DayZMapper#33]
Not sure if this project is still being updated but I've created a map.txt with image for Oring. You can download it from the link and if you're still updating then feel free to add it to the main file. Love the map tool by the way.

www.holo-federation.com/downloads2/oringdayzmapper.zip

**Comment by zamp** [comment]
Please make this into a pull request

**Comment by khamseen** [comment]
I've done that now. Sorry, I've never actually done any commits on git before so it took me a little while to figure that out.

**Comment by zamp** [comment]
You dun' good son. I appreciate.
