### ISSUE TITLE
Getting offsets and scales

### ISSUE THREAD

**Issue by ihatetn931** [zamp/DayZMapper#4]
How do i get the x and y offset as well as the map x scale and the map y scale, i'm trying to add the Takistan map to this but i dunno how to get those.

100 // X offset of the image. 0 coordinate is 100 meters away from the left edge
30 // Y offset of the image. 0 coordinate is 30 meters away from the bottom edge
1000 // map X scale. how many meters are on the map X axis
1000 // map Y scale. how many meters are on the map Y axis

**Comment by zamp** [comment]
You need to guestimate the values. After getting them somewhat close you need to calibrate the values by going in game and finding a crossroad or other easily spottable landmark. Then you can adjust the values to give you a more accurate reading.
